"""Initial migration.

Revision ID: 3a485c988199
Revises: 52a401750a76
Create Date: 2024-08-07 01:35:07.809497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a485c988199'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
